# Generated by Django 4.1.3 on 2023-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
