# Generated by Django 4.1.3 on 2023-08-17 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_createuser_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='birth_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
