# Generated by Django 4.1.3 on 2023-08-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('before_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcardphoto',
            name='id_card',
            field=models.CharField(max_length=100000),
        ),
    ]
